feat(server): Add PUT /:brotherID endpoint on backend
williamtnguyen/SJSU-TT pull request #52
Opened 2020-10-15 05:53 UTC by donieypon

Added a PUT endpoint on backend, still need to discuss on what fields
brothers can edit (e.g., password, bio, etc.).

Closes #40 :)

2020-10-15 05:54 UTC, donieypon commented
Can you guys check what I got so far and lmk what you should be updated? Thanks.

2020-10-15 06:21 UTC, dtuckersuh approved these changes

2020-10-15 20:28 UTC, dtuckersuh commented
Can't think of anything else that should be updatable. Maybe email, major, and/or position?

2020-10-16 04:31 UTC, williamtnguyen commented
> Can't think of anything else that should be updatable. Maybe email, major, and/or position?

I think those make sense to add, graduateYear as well!

2020-10-16 04:35 UTC, donieypon commented
Yeah those seem like good fields to add, should those be implemented now or after we develop the individual brother page?

2020-10-16 05:21 UTC, williamtnguyen commented
> Yeah those seem like good fields to add, should those be implemented now or after we develop the individual brother page?

Now, go ahead and make those fields the ones that are updated. Force push your changes when done

2020-10-16 05:27 UTC, williamtnguyen requested changes

2020-10-16 05:27 UTC, williamtnguyen commented on routes/api/brothers/brothers.controller.js
> +  const { errors, isValid } = validateLoginInput(req.body);
This function can't be used to validate edit form, it's for login. You'll need to write a validation function for the edit page individually, let me know if you need help w this. It's a bit tricky bc users won't edit every field most of the time, so we have to account for empty inputs accordingly

2020-10-16 05:27 UTC, williamtnguyen commented on routes/api/brothers/brothers.controller.js
> +    // Form fields:
Potentially update password, biography, email, major, position, and graduateYear depending which ones are not empty from the frontend

2020-10-26 05:24 UTC, donieypon reviewed
_yoooo <3_

2020-10-26 05:58 UTC, williamtnguyen requested changes
Left some comments!

2020-10-26 05:58 UTC, williamtnguyen commented on routes/api/util/form-validation/edit.js
> +function validateEditInput(requestBody) {
One thing I just realized is if they submit the form and all inputs are empty, then nothing would update and we'd write to MongoDB for no reason. Maybe loop through the `requestBody` before checking any of the fields and iterate an `emtpyCount` variable, and if the emptyCount is the same as the requestBody size then we can add an error that says everything empty

2020-10-26 05:58 UTC, williamtnguyen commented on routes/api/util/form-validation/edit.js
> +  if (!Validator.isEmail(requestBody.email)) {
Also for all of these we'd have to check if they're not empty before considering validating them like
```
if (!isEmpty(requestBody.email) && !Validator.isEmail(requestBody.email))
```

2020-10-26 07:24 UTC, dtuckersuh commented
Fixed the edit validation details. Lmk what yall think!

2020-10-26 16:53 UTC, williamtnguyen approved these changes
🔥

2020-10-26 16:57 UTC, merged